version: '3.0'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BOT_TOKEN: ${TOKEN}
      CHAT_ID: 1098292183
      POLL_INTERVAL_HOURS: 1
      SEED_PODCASTS_FILE: /podcasts.yaml
      PYTHONUNBUFFERED: 1
    volumes:
      - ./db/seeds/podcasts.yaml:/podcasts.yaml
